import streamlit as st
from PIL import Image


def print_hi():
    st.sidebar.markdown('__How to install__')
    st.sidebar.code('$ pip install quantumcat')
    st.write('## Welcome to quantumcat!')
    st.write('A high-level cross-platform open-source '
             'quantum computing library so that the quantum community could concentrate on '
             'building quantum applications without much effort.')
    """
    [![GitHub forks](https://img.shields.io/github/forks/artificial-brain/quantumcat.svg?style=social&label=Fork&maxAge=2592000)](https://GitHub.com/artificial-brain/quantumcat/)
    """

    st.write("### Comparison of generating a random number")

    st.write('#### Qiskit')

    st.markdown("""
    ```
    from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute,IBMQ
    from qiskit.tools.monitor import job_monitor
        
    IBMQ.enable_account('ENTER API TOKEN HERE')
    provider = IBMQ.get_provider(hub='ibm-q')
        
    q = QuantumRegister(16,'q')
    c = ClassicalRegister(16,'c')
    circuit = QuantumCircuit(q,c)
    circuit.h(q) # Applies hadamard gate to all qubits
    circuit.measure(q,c) # Measures all qubits 
        
    backend = provider.get_backend('ibmq_qasm_simulator')
    result = execute(circuit, backend, shots=1)
    ```
""")

    st.write('#### quantumcat')

    st.markdown("""
        ```
        from quantumcat.applications.generator import RandomNumber
        
        result = RandomNumber(length=4, output_type=DECIMAL).execute(api='YOUR API KEY', device='IBM DEVICE NAME')
        # The above code would execute on IBM
        ```
    """)

    st.write('To execute on any platform, Just add providers paramater to execute()')

    st.markdown("""
            ```
            from quantumcat.applications.generator import RandomNumber
            from quantumcat.utils import providers

            result = RandomNumber(length=4, output_type=DECIMAL).execute(providers=providers.GOOGLE_PROVIDER)
            # The above code would execute on Google
            
            result = RandomNumber(length=4, output_type=DECIMAL).execute(providers=providers.AMAZON_PROVIDER)
            # The above code would execute on Amazon
            ```
        """)

    st.write("## Applications")
    col1, col2 = st.beta_columns(2)
    col1.subheader('Reinforcement Learning Example')
    col1.write('Teaching a computer to play Snake with Reinforcement Learning where '
               'random actions are generated by quantum property such as superposition '
               'using quantumcat.')
    video_file = open('assets/trained_snake.mp4', 'rb')
    video_bytes = video_file.read()
    col1.video(video_bytes)
    open_demo_button = col1.button('Click to open demo')

    col2.subheader('Monty Hall problem (Coming Soon)')
    col2.write('Placing randomly prize behind one of the 4 doors where the door is '
               'selected randomly using quantum property such as superposition '
               'using quantumcat.')
    video_file = open('assets/trained_snake.mp4', 'rb')
    original = Image.open('assets/monty-hall-problem.png')
    col2.image(original, use_column_width=True)


if __name__ == '__main__':
    print_hi()

